title: Welcome to my page!
description: > # this means to ignore newlines until "baseurl:"
  I will discuss a bit about my impressive Master's thesis here. 
permalink: ':title/'
baseurl: "/Master_Project" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Nazanin Rezajooei # add your name
author-img: Nazaninrzj.png # add your photo
about-author: I am a Master's student in Scientific Computing at Memorial Universuty of Newfoundland. I am developing a new method through machine learning algorithms to predict dispersion interactions of molecules.  # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: NazaninRzj # add your Github handle
social-linkedin: nazanin-rezajooei # add your Linkedin handle
social-email: nrezajooei@mun.ca # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
